#!/bin/bash
set -e

npx create-snowpack-app --template @snowpack/app-template-blank app.git

pushd app.git
    npm run build |& tee log
    npm run build |& tee log
    npm run build |& tee log
    npm run build |& tee log
    npm run build |& tee log
    npm run build |& tee log
    npm run build |& tee log
    npm run build |& tee log
    npm run build |& tee log
    npm run build |& tee log
    npm run build |& tee log
    npm run build |& tee log
    npm run build |& tee log
    npm run build |& tee log
    npm run build |& tee log
    npm run build |& tee log
    npm run build |& tee log
    npm run build |& tee log
    npm run build |& tee log
    npm run build |& tee log
    npm run build |& tee log
    npm run build |& tee log
    npm run build |& tee log
    npm run build |& tee log
    npm run build |& tee log
    npm run build |& tee log
    npm run build |& tee log
    npm run build |& tee log
    npm run build |& tee log
    npm run build |& tee log
    npm run build |& tee log
    npm run build |& tee log
    npm run build |& tee log
    npm run build |& tee log
    npm run build |& tee log
    npm run build |& tee log
    npm run build |& tee log
    npm run build |& tee log
    npm run build |& tee log
    npm run build |& tee log
    npm run build |& tee log
    npm run build |& tee log
    npm run build |& tee log
    npm run build |& tee log
    npm run build |& tee log
    npm run build |& tee log
    npm run build |& tee log
    npm run build |& tee log
    npm run build |& tee log
    npm run build |& tee log
    npm run build |& tee log
    npm run build |& tee log
    npm run build |& tee log
    npm run build |& tee log
    npm run build |& tee log
    npm run build |& tee log
    npm run build |& tee log
    npm run build |& tee log
    npm run build |& tee log
    npm run build |& tee log
    npm run build |& tee log
    npm run build |& tee log
    npm run build |& tee log
    npm run build |& tee log
    npm run build |& tee log
    npm run build |& tee log
    npm run build |& tee log
    npm run build |& tee log
    npm run build |& tee log
    npm run build |& tee log
    npm run build |& tee log
    npm run build |& tee log
    npm run build |& tee log
    npm run build |& tee log
    npm run build |& tee log
    npm run build |& tee log
    npm run build |& tee log
    npm run build |& tee log
    npm run build |& tee log
    npm run build |& tee log
    npm run build |& tee log
    npm run build |& tee log
    npm run build |& tee log
    npm run build |& tee log
    npm run build |& tee log
    npm run build |& tee log
    npm run build |& tee log
    npm run build |& tee log
    npm run build |& tee log
    npm run build |& tee log
    npm run build |& tee log
    npm run build |& tee log
    npm run build |& tee log
    npm run build |& tee log
    npm run build |& tee log
    npm run build |& tee log
    npm run build |& tee log
    npm run build |& tee log
    npm run build |& tee log
    npm run build |& tee log
    npm run build |& tee log
    npm run build |& tee log
    npm run build |& tee log
    npm run build |& tee log
    npm run build |& tee log
    npm run build |& tee log
    npm run build |& tee log
    npm run build |& tee log
    npm run build |& tee log
    npm run build |& tee log
    npm run build |& tee log
    npm run build |& tee log
    npm run build |& tee log
    npm run build |& tee log
    npm run build |& tee log
    npm run build |& tee log
    npm run build |& tee log
    npm run build |& tee log
    npm run build |& tee log
    npm run build |& tee log
    npm run build |& tee log
    npm run build |& tee log
    npm run build |& tee log
    npm run build |& tee log
    npm run build |& tee log
    npm run build |& tee log
    npm run build |& tee log
    npm run build |& tee log
popd
