name: test @idangazit/snowbank

on:
  push:
  schedule:
    - cron: '15 * * * *'
  workflow_dispatch:

jobs:
  npm-run-build-templates:
    strategy:
      matrix:
        template:
          ['@idangazit/snowbank']
        os: [macos-latest, ubuntu-latest, windows-latest]
    runs-on: ${{matrix.os}}
    steps:
      - uses: actions/checkout@v2
      - name: create-snowpack-app
        run: |
          npx create-snowpack-app --template ${{matrix.template}} app
          cd app
          npm run build
