name: continuous audit

on:
  push:
  schedule:
    - cron: '*/30 * * * *'

jobs:
  npm-run-build-templates:
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
        template: [11ty, blank, blank-typescript, lit-element, lit-element-typescript, minimal, preact, react, react-typescript, svelte, svelte-typescript, vue, vue-typescript]
    runs-on: ${{matrix.os}}
    steps:
      - uses: actions/checkout@v1
      - name: create-snowpack-app
        run: |
          npx create-snowpack-app --template @snowpack/app-template-${{matrix.template}} app
          cd app
          ../npm-run-build-retry-intermittent.sh
