name: continuous audit

on:
  push:
  schedule:
    - cron: '0/10 * * * *'
  workflow_dispatch:

jobs:
  npm-run-build-templates:
    strategy:
      matrix:
        template: [11ty, blank, blank-typescript, lit-element, lit-element-typescript, minimal, preact, preact-typescript, react, react-typescript, svelte, svelte-typescript, vue, vue-typescript]
        os: [macos-latest, ubuntu-latest, windows-latest]
    runs-on: ${{matrix.os}}
    steps:
      - uses: actions/checkout@v2
      - name: create-snowpack-app
        run: |
          npx create-snowpack-app --template @snowpack/app-template-${{matrix.template}} app
          cd app
          npm run build
