name: continuous audit

on:
  schedule:
    - cron: '*/10 * * * *'

jobs:
  npm-run-build-templates:
    strategy:
      matrix:
        os: [ubuntu-latest, win-latest, macos-latest]
        template: [preact, preact-typescript]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v1
      - name: create-snowpack-app
        run: |
          npx create-snowpack-app --template @snowpack/app-template-${{ matrix.template }} app
          cd app
          npm run build
