name: continuous audit

on:
  push:
  schedule:
    - cron: '*/30 * * * *'

jobs:
  npm-run-build-templates:
    strategy:
      matrix:
        os: [ubuntu-latest]
        template: [11ty, blank, lit-element, minimal, preact, react, svelte, vue]
    runs-on: ${{matrix.os}}
    steps:
      - uses: actions/checkout@v1
      - name: create-snowpack-app
        run: |
          npx create-snowpack-app --template @snowpack/app-template-${{matrix.template}} app
          cd app
          ../npm-run-build-retry-intermittent.sh
