name: test snowpack blank template

on:
  push:
  schedule:
    - cron: '20 * * * *'

jobs:

  test_blank:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: create-snowpack-app
      run: |
        npx create-snowpack-app --template @snowpack/app-template-blank app
    - name: npm run build
      run:  |
        cd app
        npm run build
