name: test snowpack react template

on:
  push:
  schedule:
    - cron: '*/5 * * * *'

jobs:

  test_react:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: create-snowpack-app
      run: |
        npx create-snowpack-app --template @snowpack/app-template-react app
    - name: npm run build
      run:  |
        cd app
        npm run build
