name: snowpack v3 test svelte-tailwind-snowpack template

on:
  push:
  schedule:
    - cron: '0/15 * * * *'
  workflow_dispatch:

jobs:
  npm-run-build-templates:
    strategy:
      matrix:
        template:
          [svelte-tailwind-snowpack]
        os: [macos-latest, ubuntu-latest, windows-latest]
    runs-on: ${{matrix.os}}
    steps:
      - uses: actions/checkout@v2
      - name: create-snowpack-app
        run: |
          npx create-snowpack-app --template ${{matrix.template}} app
          cd app
          npm run build
