name: test snowpack templates

on:
  push:
  schedule:
    - cron: '20 * * * *'

jobs:
  npm_run_build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: build
      run: |
        npx create-snowpack-app --template @snowpack/app-template-svelte-typescript app
        cd app
        npm run build
