name: test snowpack templates

on:
  push:
  schedule:
    - cron: '*/5 * * * *'

jobs:

  test_11ty:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: create-snowpack-app
      run: |
        npx create-snowpack-app --template @snowpack/app-template-11ty app
    - name: npm run build
      run:  |
        cd app
        npm run build

  test_blank_retry_intermittent:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: create-snowpack-app
      run: |
        npx create-snowpack-app --template @snowpack/app-template-blank app
    - name: npm run build
      run:  |
        cd app
        ../npm-run-build-retry-intermittent.sh

  test_blank_typescript:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: create-snowpack-app
      run: |
        npx create-snowpack-app --template @snowpack/app-template-blank-typescript app
    - name: npm run build
      run:  |
        cd app
        npm run build

  test_lit_element:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: create-snowpack-app
      run: |
        npx create-snowpack-app --template @snowpack/app-template-lit-element app
    - name: npm run build
      run:  |
        cd app
        npm run build

  test_lit__element_typescript:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: create-snowpack-app
      run: |
        npx create-snowpack-app --template @snowpack/app-template-lit-element-typescript app
    - name: npm run build
      run:  |
        cd app
        npm run build

  test_minimal:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: create-snowpack-app
      run: |
        npx create-snowpack-app --template @snowpack/app-template-minimal app
    - name: npm run build
      run:  |
        cd app
        npm run build

  test_preact_retry_intermittent:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: create-snowpack-app
      run: |
        npx create-snowpack-app --template @snowpack/app-template-preact app
    - name: npm run build
      run:  |
        cd app
        ../npm-run-build-retry-intermittent.sh

  test_preact_typescript_with_chai_and_1_jest:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: create-snowpack-app
      run: |
        npx create-snowpack-app --template @snowpack/app-template-preact-typescript app
    - name: npm i @types/chai
      run:  |
        cd app
        npm i @types/chai
    - name: npm i @types/jest
      run:  |
        cd app
        npm i @types/jest
    - name: npm run build
      run:  |
        cd app
        npm run build

  test_preact_typescript_with_chai_and_2_mocha:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: create-snowpack-app
      run: |
        npx create-snowpack-app --template @snowpack/app-template-preact-typescript app
    - name: npm i @types/chai
      run:  |
        cd app
        npm i @types/chai
    - name: npm i @types/mocha
      run:  |
        cd app
        npm i @types/mocha
    - name: npm run build
      run:  |
        cd app
        npm run build

  test_react_retry_intermittent:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: create-snowpack-app
      run: |
        npx create-snowpack-app --template @snowpack/app-template-react app
    - name: npm run build
      run:  |
        cd app
        ../npm-run-build-retry-intermittent.sh

  test_react_typescript:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: create-snowpack-app
      run: |
        npx create-snowpack-app --template @snowpack/app-template-react-typescript app
    - name: npm run build
      run:  |
        cd app
        npm run build

  test_svelte_retry_intermittent:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: create-snowpack-app
      run: |
        npx create-snowpack-app --template @snowpack/app-template-svelte app
    - name: npm run build
      run:  |
        cd app
        ../npm-run-build-retry-intermittent.sh

  test_svelte_typescript:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: create-snowpack-app
      run: |
        npx create-snowpack-app --template @snowpack/app-template-svelte-typescript app
    - name: npm run build
      run:  |
        cd app
        npm run build

  test_vue_retry_intermittent:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: create-snowpack-app
      run: |
        npx create-snowpack-app --template @snowpack/app-template-vue app
    - name: npm run build
      run:  |
        cd app
        ../npm-run-build-retry-intermittent.sh

  test_vue_typescript_retry_intermittent:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: create-snowpack-app
      run: |
        npx create-snowpack-app --template @snowpack/app-template-vue-typescript app
    - name: npm run build
      run:  |
        cd app
        ../npm-run-build-retry-intermittent.sh
