name: test snowpack templates

on:
  push:
  schedule:
    - cron: '20 10 * * *'

jobs:

  _11ty:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: create-snowpack-app
      run: |
        npx create-snowpack-app --template @snowpack/app-template-11ty app
    - name: npm run build
      run:  |
        cd app
        ../npm-run-build-retry-intermittent.sh

  blank:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: create-snowpack-app
      run: |
        npx create-snowpack-app --template @snowpack/app-template-blank app
    - name: npm run build
      run:  |
        cd app
        ../npm-run-build-retry-intermittent.sh

  blank-typescript:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: create-snowpack-app
      run: |
        npx create-snowpack-app --template @snowpack/app-template-blank-typescript app
    - name: npm run build
      run:  |
        cd app
        ../npm-run-build-retry-intermittent.sh

  lit-element:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: create-snowpack-app
      run: |
        npx create-snowpack-app --template @snowpack/app-template-lit-element app
    - name: npm run build
      run:  |
        cd app
        ../npm-run-build-retry-intermittent.sh

  lit-element-typescript:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: create-snowpack-app
      run: |
        npx create-snowpack-app --template @snowpack/app-template-lit-element-typescript app
    - name: npm run build
      run:  |
        cd app
        ../npm-run-build-retry-intermittent.sh

  minimal:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: create-snowpack-app
      run: |
        npx create-snowpack-app --template @snowpack/app-template-minimal app
    - name: npm run build
      run:  |
        cd app
        ../npm-run-build-retry-intermittent.sh

  preact:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: create-snowpack-app
      run: |
        npx create-snowpack-app --template @snowpack/app-template-preact app
    - name: npm run build
      run:  |
        cd app
        ../npm-run-build-retry-intermittent.sh

  preact-typescript:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: create-snowpack-app
      run: |
        npx create-snowpack-app --template @snowpack/app-template-preact-typescript app
        cd app
    - name: npm run build
      run: |
        cd app
        ../npm-run-build-retry-intermittent.sh

  react:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: create-snowpack-app
      run: |
        npx create-snowpack-app --template @snowpack/app-template-react app
    - name: npm run build
      run:  |
        cd app
        ../npm-run-build-retry-intermittent.sh

  react-typescript:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: create-snowpack-app
      run: |
        npx create-snowpack-app --template @snowpack/app-template-react-typescript app
    - name: npm run build
      run:  |
        cd app
        ../npm-run-build-retry-intermittent.sh

  svelte:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: create-snowpack-app
      run: |
        npx create-snowpack-app --template @snowpack/app-template-svelte app
    - name: npm run build
      run:  |
        cd app
        ../npm-run-build-retry-intermittent.sh

  svelte-typescript:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: create-snowpack-app
      run: |
        npx create-snowpack-app --template @snowpack/app-template-svelte-typescript app
    - name: npm run build
      run: |
        cd app
        ../npm-run-build-retry-intermittent.sh

  vue:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: create-snowpack-app
      run: |
        npx create-snowpack-app --template @snowpack/app-template-vue app
    - name: npm run build
      run:  |
        cd app
        ../npm-run-build-retry-intermittent.sh

  vue-typescript:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: create-snowpack-app
      run: |
        npx create-snowpack-app --template @snowpack/app-template-vue-typescript app
    - name: npm run build
      run:  |
        cd app
        ../npm-run-build-retry-intermittent.sh
