name: test snowpack templates

on:
  push:
  schedule:
    - cron: '*/5 * * * *'

jobs:

  test_11ty:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: create-snowpack-app
      run: |
        npx create-snowpack-app --template @snowpack/app-template-11ty app
    - name: npm run build
      run:  |
        cd app
        npm run build

  test_blank:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: create-snowpack-app
      run: |
        npx create-snowpack-app --template @snowpack/app-template-blank app
    - name: npm run build
      run:  |
        cd app
        npm run build

  test_blank_typescript:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: create-snowpack-app
      run: |
        npx create-snowpack-app --template @snowpack/app-template-blank-typescript app
    - name: npm run build
      run:  |
        cd app
        npm run build

  test_lit_element:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: create-snowpack-app
      run: |
        rm -rf app
        npx create-snowpack-app --template @snowpack/app-template-lit-element app
    - name: npm run build
      run:  |
        cd app
        npm run build

  test_lit__element_typescript:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: create-snowpack-app
      run: |
        rm -rf app
        npx create-snowpack-app --template @snowpack/app-template-lit-element-typescript app
    - name: npm run build
      run:  |
        cd app
        npm run build

  test_minimal:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: create-snowpack-app
      run: |
        rm -rf app
        npx create-snowpack-app --template @snowpack/app-template-minimal app
    - name: npm run build
      run:  |
        cd app
        npm run build

  test_preact:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: create-snowpack-app
      run: |
        rm -rf app
        npx create-snowpack-app --template @snowpack/app-template-preact app
    - name: npm run build
      run:  |
        cd app
        npm run build

  test_preact_typescript:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: create-snowpack-app
      run: |
        rm -rf app
        npx create-snowpack-app --template @snowpack/app-template-preact-typescript app
    - name: npm run build
      run:  |
        cd app
        npm run build

  test_react:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: create-snowpack-app
      run: |
        rm -rf app
        npx create-snowpack-app --template @snowpack/app-template-react app
    - name: npm run build
      run:  |
        cd app
        npm run build

  test_react_typescript:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: create-snowpack-app
      run: |
        rm -rf app
        npx create-snowpack-app --template @snowpack/app-template-react-typescript app
    - name: npm run build
      run:  |
        cd app
        npm run build

  test_svelte:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: create-snowpack-app
      run: |
        rm -rf app
        npx create-snowpack-app --template @snowpack/app-template-svelte app
    - name: npm run build
      run:  |
        cd app
        npm run build

  test_svelte_typescript:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: create-snowpack-app
      run: |
        rm -rf app
        npx create-snowpack-app --template @snowpack/app-template-svelte-typescript app
    - name: npm run build
      run:  |
        cd app
        npm run build

  test_vue:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: create-snowpack-app
      run: |
        rm -rf app
        npx create-snowpack-app --template @snowpack/app-template-vue app
    - name: npm run build
      run:  |
        cd app
        npm run build

  test_vue_typescript:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: create-snowpack-app
      run: |
        rm -rf app
        npx create-snowpack-app --template @snowpack/app-template-vue-typescript app
    - name: npm run build
      run:  |
        cd app
        npm run build
