name: test other snowpack templates

on:
  push:
  schedule:
    - cron: '20 10 * * *'

jobs:

  snowpack-app-template-preact-hmr-tailwind:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: create-snowpack-app
      run: |
        npx create-snowpack-app --template snowpack-app-template-preact-hmr-tailwind app
    - name: npm run build
      run: |
        cd app
        ../npm-run-build-retry-intermittent.sh

  snowpack-react-tailwind:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: create-snowpack-app
      run: |
        npx create-snowpack-app --template snowpack-react-tailwind app
    - name: npm run build
      run: |
        cd app
        ../npm-run-build-retry-intermittent.sh
