name: test snowpack templates

on:
  push:
  schedule:
    - cron: '20 * * * *'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: create-snowpack-app
      run: |
        npx create-snowpack-app --template @snowpack/app-template-svelte-typescript app
    - name: npm run build
      run:  |
        cd app
        npm run build
